name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a String
        run: echo "Hello World"
      - name: Create Directory
        run: |
          mkdir -p srikanth
          ls -lah
          node -v
          npm -v