name: Shell Commands

on:
  pull_request:
    types: [closed]

jobs:
  merge-PR:
    if: github.event.pull_request.merged == true
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a String
        run: echo "Hello Srikanth"
      - name: Create Directory
        run: |
          mkdir -p Srikanth
          touch file-srikanth
          ls -lah
          node -v
          npm -v