name: Shell Commands

on:
  pull_request:
    types: [closed]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a String
        run: echo "Hello Srikanth"
      - name: Create Directory
        run: |
          mkdir -p Srikanth
          touch file-srikanth
          ls -lah
             